Adding second-level APIs
ponder-lab/ML pull request #29
Opened 2023-06-20 20:37 UTC by tatianacv

Adding second-level APIs. Refer to https://github.com/ponder-lab/Hybridize-Functions-Refactoring/wiki/TF2-tensor-generators

2023-06-22 14:00 UTC, khatchad requested changes

2023-06-22 14:00 UTC, khatchad commented on com.ibm.wala.cast.python.ml/source/com/ibm/wala/cast/python/ml/client/PythonTensorAnalysisEngine.java
> +              else if (Objects.equal(tensorFlowAPI, "uniform")
I feel like this code needs to be in a loop with a variable index or the `level`. There looks like there's too much repetition. But, I wouldn't do this straight-away; it sounds like like we have a bug elsewhere that is affecting this.

2023-06-26 22:56 UTC, khatchad commented
I don't think we are doing it this way anymore, correct?

2023-06-26 22:56 UTC, closed without merging

2023-06-27 02:55 UTC, tatianacv commented
> I don't think we are doing it this way anymore, correct?

Correct.